"""create books table

Revision ID: 2bc26a7ec296
Revises: b97ac0874b02
Create Date: 2022-02-15 15:53:19.488933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc26a7ec296'
down_revision = 'b97ac0874b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_books', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_books')
    # ### end Alembic commands ###
