"""create authors table

Revision ID: 88cef0380eca
Revises: 
Create Date: 2022-02-12 13:57:10.637742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cef0380eca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_author', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_books', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_books')
    op.drop_table('blog_authors')
    # ### end Alembic commands ###
