"""create book table

Revision ID: 8b559402a7d8
Revises: 36f478283ff2
Create Date: 2022-02-12 14:26:56.208415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b559402a7d8'
down_revision = '36f478283ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_books', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_books')
    # ### end Alembic commands ###
