"""create book table

Revision ID: b92eeb528aea
Revises: 076a36f1d4f5
Create Date: 2022-02-10 21:24:03.976776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92eeb528aea'
down_revision = '076a36f1d4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
