"""create books table

Revision ID: db29dd4e4859
Revises: cc1a30a01e92
Create Date: 2022-02-10 15:19:36.576834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db29dd4e4859'
down_revision = 'cc1a30a01e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
