"""create authors table

Revision ID: ff87950d76e7
Revises: 
Create Date: 2022-02-11 21:30:12.216507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff87950d76e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_author', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name_author')
    )
    op.create_table('blog_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name_books', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name_books')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_books')
    op.drop_table('blog_authors')
    # ### end Alembic commands ###
